### ISSUE TITLE
should `AbstractVAE` functions be defined in seperate file and not in `src/models/vae.jl`?

### ISSUE THREAD

**Issue by nmheim** [nmheim/GenerativeModels.jl#3]

**Comment by honzabim** [comment]
I would say that there should be a separate file for every type if there is at least one function defined for it. If not, I would stick it to some kind of main.

**Comment by nmheim** [comment]
great, I agree, will do!

**Comment by nmheim** [comment]
closed with ff3a3c421f3ebd29f2ce771990b2c9c3de343845
