### ISSUE TITLE
Batch in rand as a kwarg?

### ISSUE THREAD

**Issue by vitskvara** [nmheim/GenerativeModels.jl#30]
What is the reason for batchsize in gaussian and cgaussian being a keyword argument? I would rather make it an optional positional one.

https://github.com/nmheim/GenerativeModels.jl/blob/59e8145e373ae18e9857ea1a50e050411026a19b/src/pdfs/gaussian.jl#L40-L44

**Comment by nmheim** [comment]
Just a personal preference of mine, if you like positional args better, please go ahead and change them :)

**Comment by vitskvara** [comment]
Also, maybe rename this to `batchsize`? I think of `batch` as a collection of `batchsize` samples.

**Comment by nmheim** [comment]
you have a point. as we are calling all the other lenghts `xlength` etc, should we go with `batchlength` or `blength`? I don't really like `batchlength`/`blength` though...

**Comment by vitskvara** [comment]
Me neither :) also, `xlength` and `zlength` are actually the dimensions of the space (number of rows), while `batchsize` is the number of samples (number of columns), so I feel it is ok.

**Comment by vitskvara** [comment]
I took the liberty and already incorporated this in the gan branch that is ready to be merged.

**Comment by nmheim** [comment]
closed with 426efc6790ce73b7131982c1860a67c92de89aef
