### ISSUE TITLE
Clean up mmd

### ISSUE THREAD

**Issue by vitskvara** [nmheim/GenerativeModels.jl#67]
It was fixed and is now used from IPMeasures.jl, so there is some unnecessary stuff.

**Comment by vitskvara** [comment]
I deleted the old stuff and reimplemented mmd via IPMeasures for VAEs. I implemented 2 versions of mmd - `mmd_mean` and `mmd_rand`, depending on whether only the mean of encoder is used or if it is actually sampled from it, but I am not sure what difference it makes in training.

**Comment by vitskvara** [comment]
Nevertheless, training via mmd is still not working due to https://github.com/JuliaLang/julia/issues/31427

**Comment by nmheim** [comment]
mmd training fixed with 1d48d8e0065c59e9c6cc7a3974dec66598a5413e . if we are happy with the mmd interface I will close this. @smidl ?

**Comment by vitskvara** [comment]
It's fine with me now.
