### ISSUE TITLE
ImpIement convolutional VAE.

### ISSUE THREAD

**Issue by vitskvara** [nmheim/GenerativeModels.jl#68]
~~Implement encoder/decoder constructor.~~

~~Implement loglikelihoods etc. for 4D tensors.~~

~~Make sure everything works on GPU.~~

**Comment by vitskvara** [comment]
Should the `conv_encoder` and `conv_decoder` functions be part of this package or in GMExtensions.jl?

**Comment by vitskvara** [comment]
Convolutional decoder output has to be taken care of in `ConditionalDists.jl`.

**Comment by nmheim** [comment]
I vote for GMExtentsions :)

**Comment by vitskvara** [comment]
Moved to GMExtensions.
