### ISSUE TITLE
Slow compilation/loading

### ISSUE THREAD

**Issue by vitskvara** [nmheim/GenerativeModels.jl#8]
Can something be done with the slow compilation and loading times? From my tests is seems it is caused by Flux, DifferentialEquations and DiffEqFlux packages. It takes more than a minute to compile the package and almost half of that time is caused by using DifferentialEquations.

**Comment by nmheim** [comment]
This is bothering me as well. Its also caused by PyPlot. I have not checked how to do it yet, but it should be possible to have optional dependencies that are only loaded if one imports certain functions with [`Requires.jl`](https://github.com/MikeInnes/Requires.jl).

**Comment by nmheim** [comment]
got loading time from ~70s down to ~5s by using `Requires.jl` to optionally depend on PyPlot/DiffEqFlux/DifferentialEquations. The functionality that needs theses packages will only be available is the corresponding package is loaded. Should we continue doing it like this?

**Comment by vitskvara** [comment]
Cool, this makes a lot of things easier.
