### ISSUE TITLE
Generalize `elbo` for `AbstractVAE`

### ISSUE THREAD

**Issue by nmheim** [nmheim/GenerativeModels.jl#9]
should be possible by introducing `KL(m::AbstractVAE)`

**Comment by honzabim** [comment]
Well, I am not sure here as it will depend on how it is computed for particular VAE... depending on the distribution, whether you want to have the Beta in there, or ARD etc. I think that this is something every VAE should implement but I am not sure we can come up with a generalized method...

**Comment by smidl** [comment]
That is why we have functions encoder_mean_variance(). Each subtype redefine those, but elbo should be general.

**Comment by nmheim** [comment]
done in #24
